// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA4aGdyhoWO_yEhSgA9L_nU-reV8jLLdY',
    appId: '1:818356579042:android:956bff11164382751e0cbb',
    messagingSenderId: '818356579042',
    projectId: 'aimedic-ffa1b',
    storageBucket: 'aimedic-ffa1b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNQYtGqzrfqqW5l7vBWl3V2S7regQ3xE',
    appId: '1:818356579042:web:02e0ee1ad4cd1a1e1e0cbb',
    messagingSenderId: '818356579042',
    projectId: 'aimedic-ffa1b',
    authDomain: 'aimedic-ffa1b.firebaseapp.com',
    storageBucket: 'aimedic-ffa1b.firebasestorage.app',
    measurementId: 'G-D1TTD82TRR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_jAXhhdXJ117_Holu_ukWgHQ2vGsEO8',
    appId: '1:818356579042:ios:022d4bf0ccd12d621e0cbb',
    messagingSenderId: '818356579042',
    projectId: 'aimedic-ffa1b',
    storageBucket: 'aimedic-ffa1b.firebasestorage.app',
    iosBundleId: 'vn.aimedic.aimedic',
  );
}
